spring:
  jpa:
    hibernate:
      ddl-auto: validate
jwt:
  expiration-minutes: 15

nginx:
  require-proxy: true

chirp:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: true
  web-socket:
    allowed-origin: "https://chirp.pl-coding.com"